# Generated by Django 6.0 on 2025-12-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('route_start', models.CharField(max_length=150)),
                ('route_end', models.CharField(max_length=150)),
                ('route_notes', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.ManyToManyField(blank=True, to='trucks.extra')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trucks.truck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
